### PR TITLE
Add options (no-inlining, no-inlining-preds, no-simplify-clauses)

### PR DESCRIPTION
**Pull request by Hogeyama**
- `(set-options :no-inlining true)` disables inlining for all predicates.
- `(set-options :no-inlining-preds "P1 P2 ... Pn ")` disables inlining of `P1`, ..., `Pn`.
- `(set-options :no-simplify-clauses true)` disables simplification of clauses.

These options are useful for discovering good predicates.

### CODE REVIEW

**Comment by AdrienChampion** [comment]
Thank you for the PR!

@Hogeyama It looks good, can you merge with the current master to confirm all checks pass?

**Comment by AdrienChampion** [comment]
I took the liberty of updating your branch, sorry if that caused any inconvenience.

**Comment by Hogeyama** [comment]
I'm sorry for the late reply.

No problem. Thank you for merging!

**Comment by AdrienChampion** [comment]
I made a few minor changes. I also made `no-simplify-clauses` issue a warning. This is because I think the analysis assumes a the CHC have a certain shape, and that shape is a result of part of the clause simplification process.

I cannot investigate this right now, instead I hope it is enough to rely on users such as yourself to experiment with it and report bugs 🐱

**Comment by AdrienChampion** [comment]
@Hogeyama I can merge if you are fine with the current state of this PR, just let me know.

**Comment by Hogeyama** [comment]
> I think the analysis assumes a the CHC have a certain shape, and that shape is a result of part of the clause simplification process.

OK. I'll keep it in my mind.

> @Hogeyama I can merge if you are fine with the current state of this PR, just let me know.

Sorry for late reply again. I'm fine, thank you.

**Pull request merged**
